name: global
dependencies:
  - fzf
  - bat
  - chezmoi
  - dive
  - eza
  - fd-find
  - k9s
  - kubelogin
  - kubernetes-client
  - kubernetes-helm
  - lazygit
  - requests
  - ripgrep
  - terraform
  - tflint
  - vault
  - yazi
  - yq
  - zoxide
  - python=3.13
  - nodejs
  - go-jsonnet
  - jsonnet-language-server
  - jsonnet-bundler
  - grizzly
  - kube-no-trouble
  - uv
